language: go
go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
services:
  - postgresql
install:
  - go get -t ./...
before_script:
  - psql -c 'create database bsql_test;' -U postgres
script:
  - |
    if [[ $(go version) == *1.12* ]]; then
      go test -v -covermode=count -coverprofile=coverage.out ./... &&
      go get github.com/mattn/goveralls &&
      $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
    else
      go test -v ./...
    fi
notifications:
  email:
    applejava@qq.com
